version: '3.8'

networks:
  # Specify the network for bridging
  app-network:
    driver: bridge

services:
  maker-client:
    build: ./src/maker-service/
    command: node 
    environment:
      NODE_ENV: 'development'
    volumes:
      - './package.json:/home/maker-client/package.json'
    # restart: always
    networks:
      - app-network