version: '3.8'

networks:
  # Specify the network for bridging
  app-network:
    driver: bridge

services:
  maker-client:
    build: .
    command: npm run maker:start
    environment:
      NODE_ENV: 'development'
    restart: always
    networks:
      - app-network